Select dynamic_parser.selector_name, transformation_routine.target_object, transformation_routine.order_id as routine_order_id, transformation_procedure.id, transformation_procedure.order_id as procedure_order_id, transformation_procedure.transformation_method, param_entry.left_value, param_entry.right_value 
FROM dynamic_parser
JOIN dynamic_parser_transformation_routine ON dynamic_parser.id = dynamic_parser_transformation_routine.dynamic_parser_routines_id
JOIN transformation_routine ON transformation_routine.id = dynamic_parser_transformation_routine.transformation_routine_id
JOIN transformation_routine_transformation_procedure ON transformation_routine.id = transformation_routine_transformation_procedure.transformation_routine_procedures_id 
JOIN transformation_procedure ON transformation_routine_transformation_procedure.transformation_procedure_id = transformation_procedure.id
JOIN transformation_procedure_param_entry_wrapper ON transformation_procedure_param_entry_wrapper.transformation_procedure_parameter_wrappers_id = transformation_procedure.id
JOIN param_entry_wrapper ON transformation_procedure_param_entry_wrapper.param_entry_wrapper_id = param_entry_wrapper.id
JOIN param_entry_wrapper_param_entry ON param_entry_wrapper.id = param_entry_wrapper_param_entry.param_entry_wrapper_parameters_id
JOIN param_entry ON param_entry_wrapper_param_entry.param_entry_id = param_entry.id